raw = {'BERD@NFDI': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460037581',
                     'GitHub': '',
                     'Homepage': 'https://www.berd-nfdi.de',
                     'Inception': '2021-10-01T00:00:00Z',
                     'Twitter': 'https://twitter.com/BERD_NFDI',
                     'Wikidata': 'http://www.wikidata.org/entity/Q108542181',
                     'Zenodo': '',
                     'Linkedin': 'https://www.linkedin.com/company/berd-nfdi'},
 'DAPHNE4NFDI': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460248799',
                 'GitHub': '',
                 'Homepage': 'http://www.daphne-nfdi.de',
                 'Inception': '2021-10-01T00:00:00Z',
                 'Twitter': '',
                 'Wikidata': 'http://www.wikidata.org/entity/Q108542327',
                 'YouTube': '',
                 'Zenodo': ''},
 'DataPlant': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/442077441',
               'GitHub': 'https://github.com/nfdi4plants',
               'Homepage': 'http://nfdi4plants.de',
               'Inception': '2020-10-01T00:00:00Z',
               'Twitter': 'https://twitter.com/nfdi4plants',
               'Wikidata': 'http://www.wikidata.org/entity/Q98380336',
               'YouTube': 'https://www.youtube.com/channel/UCrTBwQWOa0-aWYkwoY104Wg',
               'Zenodo': 'https://zenodo.org/communities/nfdi4plants'},
 'FAIRmat': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460197019',
             'GitHub': '',
             'Homepage': 'https://www.fair-di.eu/fairmat/fairmat_/consortium',
             'Inception': '2021-10-01T00:00:00Z',
             'Twitter': 'https://twitter.com/FAIRmat_NFDI',
             'Wikidata': 'http://www.wikidata.org/entity/Q108542373',
             'YouTube': '',
             'Zenodo': ''},
 'GHGA': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/441914366',
          'GitHub': 'https://github.com/ghga-de',
          'Homepage': 'https://ghga.dkfz.de',
          'Inception': '2020-10-01T00:00:00Z',
          'Twitter': 'https://twitter.com/GHGA_DE',
          'Wikidata': 'http://www.wikidata.org/entity/Q98380337',
          'YouTube': '',
          'Zenodo': ''},
 'KonsortSWD': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/442494171',
                'GitHub': '',
                'Homepage': 'https://www.ratswd.de/konsortswd',
                'Inception': '2020-10-01T00:00:00Z',
                'Twitter': 'https://twitter.com/KonsortSwd',
                'Wikidata': 'http://www.wikidata.org/entity/Q98380340',
                'YouTube': '',
                'Zenodo': ''},
 'MaRDI': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460135501',
           'GitHub': '',
           'Homepage': 'https://www.mardi4nfdi.de',
           'Inception': '2021-10-01T00:00:00Z',
           'Twitter': 'https://twitter.com/mardi4nfdi',
           'Wikidata': 'http://www.wikidata.org/entity/Q108327788',
           'YouTube': '',
           'Zenodo': ''},
 'NFDI-MatWerk': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460247524',
                  'GitHub': '',
                  'Homepage': 'https://nfdi-matwerk.de',
                  'Inception': '2021-10-01T00:00:00Z',
                  'Twitter': 'https://twitter.com/NMatwerk',
                  'Wikidata': 'http://www.wikidata.org/entity/Q108542607',
                  'YouTube': '',
                  'Zenodo': ''},
 'NFDI4BioDiversity': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/442032008',
                       'GitHub': '',
                       'Homepage': 'https://www.nfdi4biodiversity.org',
                       'Inception': '2020-10-01T00:00:00Z',
                       'Twitter': 'https://twitter.com/NFDI4BioDiv',
                       'Wikidata': 'http://www.wikidata.org/entity/Q98380341',
                       'YouTube': '',
                       'Zenodo': ''},
 'NFDI4Cat': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/441926934',
              'GitHub': '',
              'Homepage': 'https://nfdi4cat.org',
              'Inception': '2020-10-01T00:00:00Z',
              'Twitter': 'https://twitter.com/NFDI4Cat',
              'Wikidata': 'http://www.wikidata.org/entity/Q98380342',
              'YouTube': '',
              'Zenodo': 'https://zenodo.org/communities/nfdi4cat'},
 'NFDI4Chem': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/441958208',
               'GitHub': 'https://github.com/NFDI4Chem',
               'Homepage': 'https://www.nfdi4chem.de',
               'Inception': '2020-10-01T00:00:00Z',
               'Twitter': 'https://twitter.com/Nfdi4Chem',
               'Wikidata': 'http://www.wikidata.org/entity/Q96678459',
               'YouTube': 'https://www.youtube.com/channel/UCQlKQDjyYFzlUFrDfR9vVJg',
               'Zenodo': ''},
 'NFDI4Culture': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/441958017',
                  'GitHub': 'https://github.com/NFDI4Culture',
                  'Homepage': 'https://nfdi4culture.de',
                  'Inception': '2020-10-01T00:00:00Z',
                  'Twitter': 'https://twitter.com/nfdi4culture',
                  'Wikidata': 'http://www.wikidata.org/entity/Q98276929',
                  'YouTube': '',
                  'Zenodo': 'https://zenodo.org/communities/nfdi4culture'},
 'NFDI4DataScience': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460234259',
                      'GitHub': '',
                      'Homepage': 'https://www.nfdi4datascience.de',
                      'Inception': '2021-10-01T00:00:00Z',
                      'Twitter': 'https://twitter.com/nfdi4ds',
                      'Wikidata': 'http://www.wikidata.org/entity/Q108542422',
                      'YouTube': '',
                      'Zenodo': ''},
 'NFDI4Earth': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460036893',
                'GitHub': '',
                'Homepage': 'https://www.nfdi4earth.de',
                'Inception': '2021-10-01T00:00:00Z',
                'Twitter': 'https://twitter.com/nfdi4earth',
                'Wikidata': 'http://www.wikidata.org/entity/Q108542504',
                'YouTube': '',
                'Zenodo': ''},
 'NFDI4Health': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/442326535',
                 'GitHub': 'https://github.com/nfdi4health',
                 'Homepage': 'https://www.nfdi4health.de',
                 'Inception': '2020-10-01T00:00:00Z',
                 'Twitter': 'https://twitter.com/NFDI4Health',
                 'Wikidata': 'http://www.wikidata.org/entity/Q98380343',
                 'YouTube': '',
                 'Zenodo': ''},
 'NFDI4Ing': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/442146713',
              'GitHub': '',
              'Homepage': 'https://nfdi4ing.de',
              'Inception': '2020-10-01T00:00:00Z',
              'Twitter': 'https://twitter.com/NFDI4Ing',
              'Wikidata': 'http://www.wikidata.org/entity/Q98380344',
              'YouTube': '',
              'Zenodo': 'https://zenodo.org/communities/nfdi4ing'},
 'NFDI4Microbiota': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460129525',
                     'GitHub': '',
                     'Homepage': 'https://nfdi4microbiota.de',
                     'Inception': '2021-10-01T00:00:00Z',
                     'Twitter': 'https://twitter.com/nfdi4microbiota',
                     'Wikidata': 'http://www.wikidata.org/entity/Q99534506',
                     'YouTube': '',
                     'Zenodo': 'https://zenodo.org/communities/nfdi4microbiota'},
 'PUNCH4NFDI': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460248186',
                'GitHub': '',
                'Homepage': 'https://www.punch4nfdi.de',
                'Inception': '2021-10-01T00:00:00Z',
                'Twitter': 'https://twitter.com/Punch4NFDI',
                'Wikidata': 'http://www.wikidata.org/entity/Q108542637',
                'YouTube': '',
                'Zenodo': ''},
 'Text+': {'GEPRIS': 'http://gepris.dfg.de/gepris/projekt/460033370',
           'GitHub': '',
           'Homepage': 'https://www.text-plus.org',
           'Inception': '2021-10-01T00:00:00Z',
           'Twitter': 'https://twitter.com/Textplus_NFDI',
           'Wikidata': 'http://www.wikidata.org/entity/Q98271443',
           'YouTube': '',
           'Zenodo': ''}
 }
